### ISSUE TITLE
Saving an entry in a large dictionary hangs

### ISSUE THREAD

**Issue by jan-niestadt** [elexis-eu/lexonomy#132]
We have a (test) dictionary with 37K+ entries. If you make a slight change to an entry and press Save, the "Saving" animation never disappears. If you changed the headword, the headword list on the left doesn't update like it should. If you check the network tab in developer tools, the save request fails after a few minutes with a HTTP 504 Gateway Timeout.

It seems the entry *is* saved correctly, because if you reload, your changes are still there, and the headword list does show the changed headword.

**Comment by iztokkosem** [comment]
I can confirm this, it happens also with my collocations dictionary, 2500 entries, but many very large ones. It might be that the size of the entry is the problem.

**Comment by mjakubicek** [comment]
Jan, is the dict available at lexonomy.eu? If so, can you please send a link?
Iztok, is it this one: https://www.lexonomy.eu/zwkaq8ym4/ ?

**Comment by iztokkosem** [comment]
Yes, that is the one.

**Comment by jan-niestadt** [comment]
Mine is this one: https://www.lexonomy.eu/z5wcscn7e/
If I need to add you as a user, just let me know what e-mail address to use.

**Comment by michmech** [comment]
I have found out what and where the problem is, yey! It has nothing to do with the size of the dictionary or of the entries. It's XSLT-related (again).

Both these dictionaries use XSLT stylesheets. The same happens on any other dictionary that uses an XSLT stylesheet. While saving an entry, at the end of the process when the entry has already been saved, Lexonomy applies the XSLT stylesheet to the XML (in order to send a HTML-formatted visualization of the entry back to the browser). This happens on line 693 in `lexonomy.js`:

```
        ops.updateEntry(db, req.params.dictID, req.body.id, req.body.content, user.email, {}, async function (adjustedEntryID, adjustedXml, changed) {
          db.close();
          var html = "";
          if (configs.xemplate._xsl) {
            html = await fluxslt().withStylesheet(configs.xemplate._xsl).runOn(adjustedXML);
```

The last line, which is line 693, throws this exception:

```
UnhandledPromiseRejectionWarning: ReferenceError: adjustedXML is not defined
```

I don't know how to fix it because I don't really understand the magic with `async` and `await`. I think @mjakubicek wrote that and might be able to fix it.

P.S. Why does this only happen while *saving* an entry and not while *reading* an entry? Because reading an entry is handled by the new Python back-end which "does" XSLT differently.

**Comment by iiegn** [comment]
you see, and i was wondering about [these lines](https://travis-ci.org/elexis-eu/lexonomy/jobs/545112766#L214) and thought, what the heck, must be the linting that is *not* doing its job right. but it seems the linting knows what it's doing :\ 
here, i think, the problem might be somewhat easier: "adjustedXml" != "adjustedXML"

**Comment by mjakubicek** [comment]
Indeed, sorry for the typo.
