### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by TejaGo** [elexis-eu/lexonomy#33]
Users will be able to include external links (= internet URLs with an optional caption) in entries. Lexonomy will make sure they are clickable when the entry is formatted for display.

**Comment by michmech** [comment]
Related to commit 806c7cd which, in my opinion, needs to be re-implemented differently, so that the hiding, abbreviation and clickability of URLs in Xonomy is optional and configurable.

Then we need some additions to Lexonomy's styling configuration for URLs: let the user configure certain elemens or attributes as clickable links and tell us where the URL (and optionally, the display text) is coming from.

**Comment by mjakubicek** [comment]
I'm closing this for now -- there is a solution in place, any https and https URL is clickable and as discussed, this doesn't harm anything.
